### ISSUE TITLE
Error building on Mac OS 10.10 (Yosemite)

### ISSUE THREAD

**Issue by michbarsinai** [ros/robot_state_publisher#22] opened 2014-11-13 13:19 UTC
While building (based on http://wiki.ros.org/indigo/Installation/OSX/Homebrew/Source), using Mac OS X.10 and home-brew, after running:

```
./src/catkin/bin/catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release
```

I get this error:

```
Scanning dependencies of target state_publisher
Scanning dependencies of target robot_state_publisher
[ 75%] [100%] Building CXX object CMakeFiles/state_publisher.dir/src/joint_state_listener.cpp.o
Building CXX object CMakeFiles/robot_state_publisher.dir/src/joint_state_listener.cpp.o
Linking CXX executable /Users/michael/ROS/ros_catkin_ws/devel_isolated/robot_state_publisher/lib/robot_state_publisher/state_publisher
Linking CXX executable /Users/michael/ROS/ros_catkin_ws/devel_isolated/robot_state_publisher/lib/robot_state_publisher/robot_state_publisher
ld: library not found for -llog4cxx
ld: library not found for -llog4cxx
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: make[2]: *** [/Users/michael/ROS/ros_catkin_ws/devel_isolated/robot_state_publisher/lib/robot_state_publisher/robot_state_publisher] Error 1*** [/Users/michael/ROS/ros_catkin_ws/devel_isolated/robot_state_publisher/lib/robot_state_publisher/state_publisher] Error 1

make[1]: *** [CMakeFiles/robot_state_publisher.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/state_publisher.dir/all] Error 2
make: *** [all] Error 2
<== Failed to process package 'robot_state_publisher':
  Command '/Users/michael/ROS/ros_catkin_ws/install_isolated/env.sh make -j8 -l8' returned non-zero exit status 2

Reproduce this error by running:
==> cd /Users/michael/ROS/ros_catkin_ws/build_isolated/robot_state_publisher && /Users/michael/ROS/ros_catkin_ws/install_isolated/env.sh make -j8 -l8

Command failed, exiting.
```

Note that log4cxx is installed:

```
ros_catkin_ws| brew install log4cxx
Warning: log4cxx-0.10.0 already installed
```

Not sure, but might be related to this: https://github.com/ros-perception/image_common/issues/28

Thanks!

**Comment by michbarsinai** [comment] 2014-11-13 13:31
More info:
The dynamic library is present in the default `ld` directory:

```
ros_catkin_ws| ls /usr/local/lib | grep log4cxx
liblog4cxx.10.dylib
liblog4cxx.a
liblog4cxx.dylib
```

**Comment by wjwwood** [comment] 2014-11-13 19:36
So, more people have been reporting this. I think that a recent change in Xcode has removed `/usr/local/lib` from the default linker path. You can probably work around this issue by adding `/usr/local/lib` to the `DYLD_LIBRARY_PATH`. Ultimately the code in `robot_state_publisher` (or potentially on of its dependencies) which actually passes `-llog4cxx` along should instead pass the full path to `log4cxx`, e.g. `/usr/local/lib/liblog4cxx.dylib`.

**Comment by michbarsinai** [comment] 2014-11-13 22:27
Thanks for the response. Sadly, this had the same results, so build still fails.
1. Where can I add the full path?
2. is the solution at https://github.com/ros/rosdistro/pull/5108 relevant? If so, how do I apply it here?

Thanks again,
Michael

**Comment by wjwwood** [comment] 2014-11-13 22:36
The linker fails with:

```
ld: library not found for -llog4cxx
```

When you do `export DYLD_LIBRARY_PATH=/usr/local/lib:$DYLD_LIBRARY_PATH` before running the build command?

**Comment by wjwwood** [comment] 2014-11-13 22:36
ros/rosdistro#5108 does not apply here, and it has been released for several months, so you should have it already.

**Comment by michbarsinai** [comment] 2014-11-13 23:17
Yes. Here is the output:

```
<== Finished processing package [176 of 185]: 'kdl_parser'

==> Processing catkin package: 'robot_state_publisher'
==> Building with env: '/Users/michael/ROS/ros_catkin_ws/install_isolated/env.sh'
Makefile exists, skipping explicit cmake invocation...
==> make cmake_check_build_system in '/Users/michael/ROS/ros_catkin_ws/build_isolated/robot_state_publisher'
==> make -j8 -l8 in '/Users/michael/ROS/ros_catkin_ws/build_isolated/robot_state_publisher'
Linking CXX shared library /Users/michael/ROS/ros_catkin_ws/devel_isolated/robot_state_publisher/lib/librobot_state_publisher_solver.dylib
[ 50%] Built target robot_state_publisher_solver
Linking CXX executable /Users/michael/ROS/ros_catkin_ws/devel_isolated/robot_state_publisher/lib/robot_state_publisher/robot_state_publisher
Linking CXX executable /Users/michael/ROS/ros_catkin_ws/devel_isolated/robot_state_publisher/lib/robot_state_publisher/state_publisher
ld: library not found for -llog4cxx
ld: library not found for -llog4cxx
clang: clang: error: error: linker command failed with exit code 1 (use -v to see invocation)linker command failed with exit code 1 (use -v to see invocation)

make[2]: make[2]: *** [/Users/michael/ROS/ros_catkin_ws/devel_isolated/robot_state_publisher/lib/robot_state_publisher/robot_state_publisher] Error 1*** [/Users/michael/ROS/ros_catkin_ws/devel_isolated/robot_state_publisher/lib/robot_state_publisher/state_publisher] Error 1

make[1]: *** [CMakeFiles/state_publisher.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/robot_state_publisher.dir/all] Error 2
make: *** [all] Error 2
<== Failed to process package 'robot_state_publisher':
  Command '/Users/michael/ROS/ros_catkin_ws/install_isolated/env.sh make -j8 -l8' returned non-zero exit status 2

Reproduce this error by running:
==> cd /Users/michael/ROS/ros_catkin_ws/build_isolated/robot_state_publisher && /Users/michael/ROS/ros_catkin_ws/install_isolated/env.sh make -j8 -l8

Command failed, exiting.
ros_catkin_ws| echo $DYLD_LIBRARY_PATH
/usr/local/lib:
ros_catkin_ws|
```

**Comment by michbarsinai** [comment] 2014-11-13 23:19
Also, the libraries are there:

```
ros_catkin_ws| ls -l /usr/local/lib/liblog4cxx.*
lrwxr-xr-x  1 michael  admin  48 Nov 12 16:06 /usr/local/lib/liblog4cxx.10.dylib -> ../Cellar/log4cxx/0.10.0/lib/liblog4cxx.10.dylib
lrwxr-xr-x  1 michael  admin  41 Nov 12 16:06 /usr/local/lib/liblog4cxx.a -> ../Cellar/log4cxx/0.10.0/lib/liblog4cxx.a
lrwxr-xr-x  1 michael  admin  45 Nov 12 16:06 /usr/local/lib/liblog4cxx.dylib -> ../Cellar/log4cxx/0.10.0/lib/liblog4cxx.dylib
```

**Comment by wjwwood** [comment] 2014-11-13 23:20
Can you rm -rf `/Users/michael/ROS/ros_catkin_ws/build_isolated/robot_state_publisher` and try again? I just want to make sure it isn't a CMake caching issue.

**Comment by michbarsinai** [comment] 2014-11-13 23:21
(rf-ing and trying again...)

**Comment by michbarsinai** [comment] 2014-11-13 23:32
yep. still fails.

**Comment by wjwwood** [comment] 2014-11-13 23:41
Well, that really doesn't make sense to me. I'll have to try and reproduce it locally I guess, but that might take me some time.

In the mean time you can try `DYLD_FALLBACK_LIBRARY_PATH`, manually adding `link_directories(/usr/local/lib)` to the `CMakeLists.txt` of `robot_state_publisher`, and/or checking out the options passed to the compiler for irregularities using `VERBOSE=1 catkin_make_isolated ...`.

**Comment by isucan** [comment] 2014-11-14 07:20
This is likely related: https://github.com/ros/robot_state_publisher/pull/21

**Comment by michbarsinai** [comment] 2014-11-14 08:28
I did as @wjwwood suggested - added the line

```
link_directories(/usr/local/lib)
```

at line 19 of src/robot_state_publisher/CMakeLists.txt

No the build works.

However, rviz fails now:

```
<== Finished processing package [177 of 185]: 'robot_state_publisher'

==> Processing catkin package: 'rviz'
==> Creating build directory: 'build_isolated/rviz'
==> Building with env: '/Users/michael/ROS/ros_catkin_ws/install_isolated/env.sh'
==> cmake /Users/michael/ROS/ros_catkin_ws/src/rviz -DCATKIN_DEVEL_PREFIX=/Users/michael/ROS/ros_catkin_ws/devel_isolated/rviz -DCMAKE_INSTALL_PREFIX=/Users/michael/ROS/ros_catkin_ws/install_isolated -DCMAKE_BUILD_TYPE=Release in '/Users/michael/ROS/ros_catkin_ws/build_isolated/rviz'
-- The C compiler identification is AppleClang 6.0.0.6000054
-- The CXX compiler identification is AppleClang 6.0.0.6000054
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Boost version: 1.56.0
-- Found the following Boost libraries:
--   filesystem
--   program_options
--   signals
--   system
--   thread
-- Found PkgConfig: /usr/local/bin/pkg-config
-- checking for modules 'OGRE;OGRE-Overlay'
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
--   package 'OGRE' not found
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
--   package 'OGRE-Overlay' not found
-- checking for module 'OGRE'
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
--   package 'OGRE' not found
CMake Error at /usr/local/Cellar/cmake/3.0.2/share/cmake/Modules/FindPkgConfig.cmake:341 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.0.2/share/cmake/Modules/FindPkgConfig.cmake:395 (_pkg_check_modules_internal)
  CMakeLists.txt:22 (pkg_check_modules)


dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
-- OGRE_PLUGIN_PATH=
-- Found OpenGL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework
-- Found PythonLibs: /usr/lib/libpython2.7.dylib (found version "2.7.6")
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
CMake Error at /usr/local/Cellar/cmake/3.0.2/share/cmake/Modules/FindQt4.cmake:1316 (message):
  Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:67 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/michael/ROS/ros_catkin_ws/build_isolated/rviz/CMakeFiles/CMakeOutput.log".
<== Failed to process package 'rviz':
  Command '/Users/michael/ROS/ros_catkin_ws/install_isolated/env.sh cmake /Users/michael/ROS/ros_catkin_ws/src/rviz -DCATKIN_DEVEL_PREFIX=/Users/michael/ROS/ros_catkin_ws/devel_isolated/rviz -DCMAKE_INSTALL_PREFIX=/Users/michael/ROS/ros_catkin_ws/install_isolated -DCMAKE_BUILD_TYPE=Release' returned non-zero exit status 1

Reproduce this error by running:
==> cd /Users/michael/ROS/ros_catkin_ws/build_isolated/rviz && /Users/michael/ROS/ros_catkin_ws/install_isolated/env.sh cmake /Users/michael/ROS/ros_catkin_ws/src/rviz -DCATKIN_DEVEL_PREFIX=/Users/michael/ROS/ros_catkin_ws/devel_isolated/rviz -DCMAKE_INSTALL_PREFIX=/Users/michael/ROS/ros_catkin_ws/install_isolated -DCMAKE_BUILD_TYPE=Release

Command failed, exiting.
```

**Comment by michbarsinai** [comment] 2014-11-14 08:31
Seems like OGRE was not installed...
Installed using `pip install ogre` and re-trying.

**Comment by michbarsinai** [comment] 2014-11-14 08:39
Failed again. As you can see at the bottom - OGRE is installed.

```
==> Processing catkin package: 'rviz'
==> Building with env: '/Users/michael/ROS/ros_catkin_ws/install_isolated/env.sh'
==> cmake /Users/michael/ROS/ros_catkin_ws/src/rviz -DCATKIN_DEVEL_PREFIX=/Users/michael/ROS/ros_catkin_ws/devel_isolated/rviz -DCMAKE_INSTALL_PREFIX=/Users/michael/ROS/ros_catkin_ws/install_isolated -DCMAKE_BUILD_TYPE=Release in '/Users/michael/ROS/ros_catkin_ws/build_isolated/rviz'
-- Boost version: 1.56.0
-- Found the following Boost libraries:
--   filesystem
--   program_options
--   signals
--   system
--   thread
-- checking for modules 'OGRE;OGRE-Overlay'
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
--   package 'OGRE' not found
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
--   package 'OGRE-Overlay' not found
-- checking for module 'OGRE'
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
--   package 'OGRE' not found
CMake Error at /usr/local/Cellar/cmake/3.0.2/share/cmake/Modules/FindPkgConfig.cmake:341 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.0.2/share/cmake/Modules/FindPkgConfig.cmake:395 (_pkg_check_modules_internal)
  CMakeLists.txt:22 (pkg_check_modules)


dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
-- OGRE_PLUGIN_PATH=
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
CMake Error at /usr/local/Cellar/cmake/3.0.2/share/cmake/Modules/FindQt4.cmake:1316 (message):
  Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:67 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/michael/ROS/ros_catkin_ws/build_isolated/rviz/CMakeFiles/CMakeOutput.log".
<== Failed to process package 'rviz':
  Command '/Users/michael/ROS/ros_catkin_ws/install_isolated/env.sh cmake /Users/michael/ROS/ros_catkin_ws/src/rviz -DCATKIN_DEVEL_PREFIX=/Users/michael/ROS/ros_catkin_ws/devel_isolated/rviz -DCMAKE_INSTALL_PREFIX=/Users/michael/ROS/ros_catkin_ws/install_isolated -DCMAKE_BUILD_TYPE=Release' returned non-zero exit status 1

Reproduce this error by running:
==> cd /Users/michael/ROS/ros_catkin_ws/build_isolated/rviz && /Users/michael/ROS/ros_catkin_ws/install_isolated/env.sh cmake /Users/michael/ROS/ros_catkin_ws/src/rviz -DCATKIN_DEVEL_PREFIX=/Users/michael/ROS/ros_catkin_ws/devel_isolated/rviz -DCMAKE_INSTALL_PREFIX=/Users/michael/ROS/ros_catkin_ws/install_isolated -DCMAKE_BUILD_TYPE=Release

Command failed, exiting.
ros_catkin_ws| pip show OGRE
---
Name: OGRe
Version: 4.5.0
Location: /usr/local/lib/python2.7/site-packages
Requires: twython
ros_catkin_ws|
```

**Comment by wjwwood** [comment] 2014-11-14 19:02
Please open a question on answers.ros.org or on rviz if you now have an rviz problem, but I think that the `link_directories` workaround is not a fix.

Also you cannot `pip install ogre`, it isn't a python package. You'll have to use `brew install ogre`.

The error you are getting with rviz is because your `DYLD_LIBRARY_PATH` is still set in your env to include `/usr/local/lib`. The problem is that most things in OS X and homebrew use the system `libjpeg` which has that symbol, but when you put `/usr/local/lib` in the `DYLD_LIBRARY_PATH` then it loads the `libjpeg` from homebrew which does not have that symbol (`__cg_jpeg_resync_to_restart`). I think that if you run this command, `brew unlink libjpeg libtiff libpng`, then rviz will build. However, this is again a workaround and cannot be used as a permanent solution.

**Comment by michbarsinai** [comment] 2014-11-15 21:13
Thanks. Rest of ticket (+KLUDGE) is at: https://github.com/ros-visualization/rviz/issues/828

**Comment by jackieokay** [comment] 2015-10-20 00:26
It sounds like the issue has been resolved and the related issue is with rviz, so I'm going to close this. Feel free to reopen if you think it's still relevant.

**Closed as completed by jackieokay** 2015-10-20 00:26 UTC
