### ISSUE TITLE
Cannot use tf_prefix parameter when update from ROS Melodic to ROS Noetic

### ISSUE THREAD

**Issue by ngkhiem97** [ros/robot_state_publisher#152] opened 2020-10-11 09:00 UTC
![Screenshot from 2020-10-11 15-58-22](https://user-images.githubusercontent.com/19190530/95674466-a097a180-0bda-11eb-9b5a-68e759c8b2ca.png)

In tf view_frames robot_state_publisher does not publish the tf_prefix of the robots even though I included in the launch file.

```
<node pkg="robot_state_publisher" type="robot_state_publisher" name="robot_state_publisher" output="screen">
       <param name="tf_prefix" value="$(arg tb1)" />
       <param name="publish_frequency" type="double" value="50.0" />
</node>
```

**Comment by droemer7** [comment] 2020-10-12 05:40
See #139. Noetic dropped tf_prefix, and #139 is requesting it to be restored. You may want to comment over there.

**Comment by sloretz** [comment] 2020-10-12 17:33
Thanks for the issue! I'll close this as a duplicate of #147. There's a similar issue for ROS 2 in #125

**Closed as completed by sloretz** 2020-10-12 17:33 UTC
