### ISSUE TITLE
recipe for target 'CMakeFiles/robot_state_publisher_solver.dir/src/robot_state_publisher.cpp.o' failed

### ISSUE THREAD

**Issue by khalid2696** [ros/robot_state_publisher#73] opened 2017-04-06 06:25 UTC
I'm trying to install ros-robot on RPi running Raspbian Jessie. When I'm building the catkin space, I'm getting the above mentioned error. All the 118 packages before this installed without any errors.

The error is based on shared pointers (maybe a bug after using urdf::*SharedPtr instead of boost::shared_ptr)

**Comment by sloretz** [comment] 2017-04-06 15:25
Would you mind posting the console output? Possibly a duplicate of #59

**Comment by khalid2696** [comment] 2017-04-06 19:26
Lots of error cropped up. PFA a part of the error log.

Of course, I cloned the recent version of robot_state_publisher. And it has the new version of the pointer - urdf::JointMimicSharedPtr instead of the boost one.

[Error.txt](https://github.com/ros/robot_state_publisher/files/903734/Error.txt)

**Comment by khalid2696** [comment] 2017-04-17 08:41
After going through source code and other blogs on similar issues, I have found the issue with urdfdom_headers. There is an issue with the migration of shared pointers from boost to c++11. Downgrading the urdfdom_headers to version 0.4.2 did the trick. Similarly, urdfdom had to be downgraded to 0.4.2  
[https://github.com/ros/urdfdom_headers/issues/32](url)

**Comment by sloretz** [comment] 2017-04-17 14:46
Thanks for  posting what fixed it. I'll close this in favor of #59.

**Closed as completed by sloretz** 2017-04-17 14:46 UTC
Labels: question

**Comment by wallEVA96** [comment] 2017-04-17 15:08
@ @sloretz   thank u, the day before yesterday  I have solve this with version 0.4.0,  I really compile, but i CANT use the rviz

**Comment by wallEVA96** [comment] 2017-04-17 15:12
thank u, the day before yesterday I have solve this with version 0.4.0, I really compile, but i CANT use the rviz @khalid2696
