### ISSUE TITLE
[ROS 2] Robot State Publisher not publishing to /tf

### ISSUE THREAD

**Issue by AndrewJSchoen** [ros/robot_state_publisher#145] opened 2020-08-20 15:37 UTC
I am running this all with the following configuration:
OS: MacOS 10.15.6
ROS Distro: Foxy
Branch: Foxy

I have a URDF that I have loaded and passed as an argument to the `robot_state_publisher` in my python launch file. 
```
...
urdf_path = my_share + '/urdfs/' + urdf_file_name

with open(urdf_path, 'r') as s:
   robot_desc = s.read()

nodes = [
        Node(package='tf2_ros',
             executable='static_transform_publisher',
             arguments=['0','0','0','0','0','0','world','base_link'],
             output='screen'),
        Node(name='robot_state_publisher',
             package='robot_state_publisher',
             executable='robot_state_publisher',
             output='screen',
             parameters=[{'robot_description': robot_desc}])
]
...
```

Everything starts fine, and I get the following output:

```
[static_transform_publisher-1] [INFO] [1597934455.701417809] [static_transform_publisher_791UMHNArh0ZSNho]: Spinning until killed publishing transform from 'world' to 'base_link'
[robot_state_publisher-2] Parsing robot urdf xml string.
[robot_state_publisher-2] Link base_link had 2 children
[robot_state_publisher-2] Link base had 0 children
[robot_state_publisher-2] Link shoulder_link had 1 children
[robot_state_publisher-2] Link upper_arm_link had 1 children
[robot_state_publisher-2] Link forearm_link had 1 children
[robot_state_publisher-2] Link wrist_1_link had 1 children
[robot_state_publisher-2] Link wrist_2_link had 1 children
[robot_state_publisher-2] Link wrist_3_link had 2 children
[robot_state_publisher-2] Link ee_link had 0 children
[robot_state_publisher-2] Link tool0 had 0 children
[robot_state_publisher-2] [INFO] [1597934455.808850933] [robot_state_publisher]: got segment base
[robot_state_publisher-2] [INFO] [1597934455.809177449] [robot_state_publisher]: got segment base_link
[robot_state_publisher-2] [INFO] [1597934455.809204256] [robot_state_publisher]: got segment ee_link
[robot_state_publisher-2] [INFO] [1597934455.809219624] [robot_state_publisher]: got segment forearm_link
[robot_state_publisher-2] [INFO] [1597934455.809233466] [robot_state_publisher]: got segment shoulder_link
[robot_state_publisher-2] [INFO] [1597934455.809247053] [robot_state_publisher]: got segment tool0
[robot_state_publisher-2] [INFO] [1597934455.809260374] [robot_state_publisher]: got segment upper_arm_link
[robot_state_publisher-2] [INFO] [1597934455.809274659] [robot_state_publisher]: got segment world
[robot_state_publisher-2] [INFO] [1597934455.809287840] [robot_state_publisher]: got segment wrist_1_link
[robot_state_publisher-2] [INFO] [1597934455.809300776] [robot_state_publisher]: got segment wrist_2_link
[robot_state_publisher-2] [INFO] [1597934455.809313744] [robot_state_publisher]: got segment wrist_3_link
```

While I get results when running 
```
ros2 topic echo /tf_static
```
I don't get any results from `/tf`. As a result, RVIZ2 fails to get the necessary transforms, despite parsing the `robot_description` correctly.

Any thoughts on what is going on here, or if I am experiencing some sort of bug?

I have included the URDF in a .txt file, in case that helps
[ur3e.txt](https://github.com/ros/robot_state_publisher/files/5104010/ur3e.txt)

**Comment by sloretz** [comment] 2020-08-20 15:55
> Any thoughts on what is going on here, or if I am experiencing some sort of bug?

Unlikely to be a bug, but I'll leave this open until I have enough info to say for sure.

First, there may be transforms on the `/tf_static` topic; `ros2 topic echo` needs the right QoS settings to get previously published messages. You can give those on the command line, but I'd recommend running `tf2_monitor` instead.

`ros2 run tf2_ros tf2_monitor`

Second, is `robot_state_publisher` getting joint states? `robot_state_publisher` uses it's knowledge of the robot description and a [subscribtion to joint states](https://github.com/ros/robot_state_publisher/tree/foxy#subscribed-topics) to publish transforms on the `/tf` and `/tf_static` topics. With the urdf you posted the only static transform would be between `wrist_3_link` and `ee_link`. All others should be on the `/tf` topic so long as `robot_state_publisher` is getting joint states.

**Comment by AndrewJSchoen** [comment] 2020-08-20 16:19
Thanks for the speedy response. 

I will start with the `joint_states`. I confirmed that the node should be receiving them:

```
> ros2 topic hz /joint_states
average rate: 5.011
	min: 0.197s max: 0.203s std dev: 0.00201s window: 6
```

![rqt_graph_viz](https://user-images.githubusercontent.com/5341396/90797621-7ad6d600-e2d6-11ea-9c26-aafd6b050d57.png)

For the `tf2_monitor`, this is the result I get back:

```
[tf2_monitor-1] All Broadcasters:
[tf2_monitor-1] 
[tf2_monitor-1] 
[tf2_monitor-1] 
[tf2_monitor-1] RESULTS: for all Frames
[tf2_monitor-1] 
[tf2_monitor-1] Frames:
[tf2_monitor-1] Frame: base, published by <no authority available>, Average Delay: 0.00041864, Max Delay: 0.000710249
[tf2_monitor-1] Frame: base_link, published by <no authority available>, Average Delay: 0.000417302, Max Delay: 0.000710726
[tf2_monitor-1] Frame: ee_link, published by <no authority available>, Average Delay: 0.000418658, Max Delay: 0.000711918
[tf2_monitor-1] Frame: tool0, published by <no authority available>, Average Delay: 0.000417923, Max Delay: 0.000710964
[tf2_monitor-1] Node: <no authority available> 20.021 Hz, Average Delay: 0.000418131 Max Delay: 0.000710964

```

Now, those show up right away. I have a node (seen in the graph as `control_node`), which takes a while to start up and begin sending JointState messages to the robot_state_publisher. If there is some sort of timeout there, might that be the issue?

**Comment by sloretz** [comment] 2020-08-20 17:34
> Now, those show up right away. I have a node (seen in the graph as control_node), which takes a while to start up and begin sending JointState messages to the robot_state_publisher. If there is some sort of timeout there, might that be the issue?

Looks like those are only the transforms for the fixed joints. I would guess the issue is a mismatch between the `joint_states` being sent by `control_node` and the ones expected by `robot_state_publisher`. Maybe `control_node` is sending joint states too infrequently? Maybe it's put the wrong time on the joint_state message? Maybe it's using different names for the joints than `robot_state_publisher` is expecting? Maybe `control_node` and `robot_state_publisher` are using incompatible QoS settings?

I don't think I have enough info to give a more useful response. Mind making a minimal reproducible example?

**Comment by AndrewJSchoen** [comment] 2020-08-20 19:30
I removed a bunch of the other stuff, and resolved the controller node that publishes `/joint_states` to the following:

```
import rclpy
from rclpy.node import Node
from sensor_msgs.msg import JointState
import math

JOINT_NAMES = ['shoulder_pan_joint', 'shoulder_lift_joint',
               'elbow_joint', 'wrist_1_joint',
               'wrist_2_joint', 'wrist_3_joint']
JOINT_INITIAL = [1.55, -1.77, 1.4, -1.19, -1.57, 0.0]
MOTION_JOINT = 2

class SimplePublisherNode(Node):
    def __init__(self):
        super(SimplePublisherNode,self).__init__('simple_js_publisher')
        self.js_pub = self.create_publisher(JointState,'/joint_states',1)
        self.js_msg = JointState(name=JOINT_NAMES,position=JOINT_INITIAL)
        self.create_timer(0.05,self.send_js)

    def send_js(self):
        time = self.get_clock().now().nanoseconds * 10**-9
        self.js_msg.position[MOTION_JOINT] = .25*math.sin(time)+JOINT_INITIAL[MOTION_JOINT]
        self.js_pub.publish(self.js_msg)

def main():
    rclpy.init(args=None)

    node = SimplePublisherNode()

    rclpy.spin(node)
``` 

I can confirm with this version, I get the same behavior, where the static/fixed transforms are published, but none of the dynamic ones. The output of `tf2_monitor` is the same. When I run `rviz`, I get the following errors. Not sure if they are helpful or relevant:
```
Warning: Invalid frame ID "forearm_link" passed to canTransform argument source_frame - frame does not exist
         at line 133 in /Users/schoen/ROS/ros2_foxy/src/ros2/geometry2/tf2/src/buffer_core.cpp
Warning: Invalid frame ID "shoulder_link" passed to canTransform argument source_frame - frame does not exist
         at line 133 in /Users/schoen/ROS/ros2_foxy/src/ros2/geometry2/tf2/src/buffer_core.cpp
Warning: Invalid frame ID "upper_arm_link" passed to canTransform argument source_frame - frame does not exist
         at line 133 in /Users/schoen/ROS/ros2_foxy/src/ros2/geometry2/tf2/src/buffer_core.cpp
Warning: Invalid frame ID "wrist_1_link" passed to canTransform argument source_frame - frame does not exist
         at line 133 in /Users/schoen/ROS/ros2_foxy/src/ros2/geometry2/tf2/src/buffer_core.cpp
Warning: Invalid frame ID "wrist_2_link" passed to canTransform argument source_frame - frame does not exist
         at line 133 in /Users/schoen/ROS/ros2_foxy/src/ros2/geometry2/tf2/src/buffer_core.cpp
```

**Comment by AndrewJSchoen** [comment] 2020-08-24 15:18
For the sake of a comparison, I did try the dummy_robot tutorial, and it seemed to work fine. That being said, all joints and frames were included in the URDF, as opposed to the mixed approach used in my example.

**Comment by AndrewJSchoen** [comment] 2020-08-24 16:09
Ok. Regarding the simple python code I shared, looks like omitting the time was maybe causing QoS to be unhappy. Adding the following line seems to have resolved the above snippet:

```
self.js_msg.header.stamp = self.get_clock().now().to_msg()
```

**Comment by sloretz** [comment] 2020-08-24 18:27
> looks like omitting the time was maybe causing QoS to be unhappy

Omitting time wouldn't change QoS, but it would cause `robot_state_publisher` to drop the joint state messages because they're not newer than the last received ones. There's a parameter `ignore_timestamp` to control this.

https://github.com/ros/robot_state_publisher/tree/ros2#parameters

Sounds like the issue is solved, so I'll close this for now.

**Closed as completed by sloretz** 2020-08-24 18:27 UTC
